# Generated by Django 2.1.11 on 2021-05-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import workflowops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('protocol_type', models.CharField(choices=[('http', 'HTTP'), ('udp', 'UDP'), ('display', 'Display')], max_length=20)),
                ('action_endpoint', models.URLField()),
                ('content_type', models.CharField(choices=[('json', 'JSON'), ('xml, XML', 'xml')], max_length=10)),
                ('protocol_method', models.CharField(choices=[('http_get', 'HTTP_GET'), ('http_post', 'HTTP_POST'), ('screen_display', 'Display')], max_length=10)),
                ('retry_count', models.IntegerField(blank=True, null=True)),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('on_success_next_task', models.TextField(blank=True, null=True)),
                ('on_failure_next_task', models.TextField(blank=True, null=True)),
                ('publish', models.TextField(blank=True, null=True)),
                ('action_message_template', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('version', models.CharField(choices=[('v1', 'Version 1'), ('v2', 'Version 2')], max_length=5)),
                ('workflow_namespace', models.CharField(max_length=100)),
                ('inputs', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowDSL',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('yaml', 'YAML'), ('json', 'JSON')], max_length=5)),
                ('file', models.FileField(max_length=255, upload_to=workflowops.models.workflow_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_dsl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflowops.WorkflowDSL'),
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflowops.Workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('workflow_namespace', 'user')},
        ),
    ]
