# Generated by Django 2.1.11 on 2021-05-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflowops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLogs',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('request_endpoint', models.URLField()),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN-PROGRESS', 'IN-PROGRESS'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED'), ('PERMANENTLY_FAILED', 'PERMANENTLY_FAILED'), ('UNKNOWN', 'UNKNOWN')], default='PENDING', max_length=20)),
                ('logs', models.TextField()),
                ('no_of_tries', models.IntegerField(blank=True, default=1, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflowops.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('inputs', models.TextField()),
                ('context', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN-PROGRESS', 'IN-PROGRESS'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflowops.Workflow')),
            ],
            options={
                'verbose_name': 'WorkflowInstance',
                'verbose_name_plural': 'WorkflowInstances',
            },
        ),
        migrations.AddField(
            model_name='tasklogs',
            name='workflow_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflowapi.WorkflowInstance'),
        ),
    ]
